version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      eslint-and-prettier:
        patterns:
          - "@eslint/*"
          - "eslint"
          - "eslint-config-prettier"
          - "prettier"
          - "typescript-eslint"
      tsconfig:
        patterns:
          - "@tsconfig/*"
      vitest:
        patterns:
          - "@vitest/*"
          - "vitest"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "ci"
      include: "scope"
    exclude-paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/main.yml"
      - ".github/workflows/nuget-publish.yml"
