name: Publish WebAssembly to npm registry
on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.13.3
  EMSDK_VERSION: 6.0.8

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          cache: true
      - uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: emscripten-core/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: .emsdk
      - run: pnpm install
      - name: Build WebAssembly
        run: pnpm run build
      - name: Publish to npm registry
        run: pnpm publish --tag latest --no-git-checks
