name: Publish WebAssembly to npm registry
on:
  release:
    types: [published]

env:
  PNPM_VERSION: 10
  NODE_VERSION: 22
  PYTHON_VERSION: 3.13
  EMSDK_VERSION: 6.0.1

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: emscripten-core/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: .emsdk
      - name: Update npm to latest version
        run: npm install -g npm@10.9.8 && npm install -g npm@11
      - run: pnpm install
      - name: Build WebAssembly
        run: pnpm run build
      - name: Publish to npm registry
        run: pnpm publish --tag latest --no-git-checks
